# Generated by Django 4.2.6 on 2023-12-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_registrationdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
